name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t my-nodejs-app:${{ github.sha }} .

      - name: Push Docker Image
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          docker tag my-nodejs-app:${{ github.sha }} my-docker-repo/my-nodejs-app:${{ github.sha }}
          docker push my-docker-repo/my-nodejs-app:${{ github.sha }}

      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v4
        with:
          manifests: |
            ./kubernetes/deployment.yaml
            ./kubernetes/service.yaml
          images: |
            my-docker-repo/my-nodejs-app:${{ github.sha }}
          kubectl-version: 'v1.26.0'

  notify:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Notify Deployment Status
        run: |
          if [ "${{ needs.build-and-deploy.result }}" == "success" ]; then
            echo "Deployment succeeded!" | notify-tool --success
          else
            echo "Deployment failed!" | notify-tool --failure
